import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Shivam's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link rel="shortcut icon" href="svgs/about2.svg" type="image/x-icon" />
       </head>
      <body style={{overflowX:"hidden"}} className={inter.className+"overflow-x-hidden"}><Navbar/>{children}</body>
    </html>
  );
}
